### ISSUE TITLE
Requirements for xs

### ISSUE THREAD

**Issue by andseeb** [rladstaetter/fhj.swengb.assignments.functional#1]
I have a problem with the first sequence of integers, namely "xs".
The requirements are:

```xs(i) < xs(i+1)```
```xs(i) + factor == xs(i + 1) (for i > 0 and i <= 1000)```

When I implement the second requirement, the Unit tests `provideCollectionWith1000Elements()` and `showCorrectSumImplementation()` fail.

Here's an example of my implementation:
For the arguments `lowerBound = 1` `upperBound = 10` and `factor = 3` it returns `1, 4, 7, 10`.
This fulfils both criteria as far as I can see.

Is there something wrong with those Unit tests or am I misunderstanding the criteria?

**Comment by rladstaetter** [comment]
you are right, it should read:

```scala
  /**
    * implement a sequence of ints, which start with lowerBound and end with
    * upperbound.
    *
    * for all elements following is true:
    *
    * xs(i) < xs(i+1)
    * xs(i) + 1 == xs(i + 1) (for i > 0 and i <= 1000)
    *
    */
  val xs: Seq[Int] = ???
```

i've updated the project.
